const STORE = 'qoldau-demo-requests';
const initial = [
  {id:'ЗТ-2026-00841',date:'25.08.2026',company:'ТОО «Almaty Build»',bin:'120840002091',object:'ЖК «Green City»',region:'г. Алматы',work:'Прокладка оптического кабеля',status:'На проверке',person:'С. Жаксылыкова',due:'27 авг.'},
  {id:'ЗТ-2026-00840',date:'25.08.2026',company:'ТОО «Urban Net»',bin:'190240009122',object:'Бизнес-центр «Orda»',region:'г. Астана',work:'Подключение к телекоммуникационной сети',status:'В работе',person:'Д. Алмазов',due:'29 авг.'},
  {id:'ЗТ-2026-00839',date:'24.08.2026',company:'ТОО «Qurylys Group»',bin:'110640003473',object:'Реконструкция ВОЛС',region:'Карагандинская область',work:'Строительство ВОЛС',status:'На согласовании',person:'Д. Омаров',due:'26 авг.'},
  {id:'ЗТ-2026-00838',date:'24.08.2026',company:'АО «КазИнвест»',bin:'050940004581',object:'Административное здание',region:'г. Алматы',work:'Размещение оборудования',status:'ТУ выдано',person:'Д. Алмазов',due:'Исполнено'},
  {id:'ЗТ-2026-00837',date:'23.08.2026',company:'ТОО «Mobile Connect»',bin:'141140008225',object:'Базовая станция № 114',region:'Туркестанская область',work:'Подвес оптического кабеля на опорах',status:'На доработке',person:'М. Бекенов',due:'28 авг.'},
  {id:'ЗТ-2026-00836',date:'22.08.2026',company:'ТОО «Jetysu Digital»',bin:'151140006321',object:'Подключение индустриальной зоны',region:'Область Жетісу',work:'Подключение к телекоммуникационной сети',status:'ТУ выдано',person:'Д. Алмазов',due:'Исполнено',tu:'Д08-08-125/Т-08/26'}
];
let requests = JSON.parse(localStorage.getItem(STORE) || 'null') || initial;
// Обновляем демонстрационные записи, сохранённые в браузере до смены регионов.
requests = requests.map(request => ({
  ...request,
  ...(request.person === 'А. Сейтова' ? {person:'Д. Алмазов'} : {}),
  ...(request.id === 'ЗТ-2026-00838' && request.status === 'ТУ выдано' ? {region:'г. Алматы'} : {})
}));
if (!requests.some(request => request.id === 'ЗТ-2026-00836')) requests.push(initial.at(-1));
localStorage.setItem(STORE, JSON.stringify(requests));
let view = 'overview';
const app = document.querySelector('#app'); const dialog = document.querySelector('#request-dialog'); const details = document.querySelector('#detail-dialog');
const esc = value => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const statusClass = s => ({'На проверке':'s-new','В работе':'s-work','На согласовании':'s-agree','ТУ выдано':'s-issued','На доработке':'s-fix'}[s] || 's-new');
function save(){localStorage.setItem(STORE,JSON.stringify(requests));}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function pageHead(title, subtitle, button=''){return `<div class="page-head"><div><p class="overline">АО «Казахтелеком» · Технические условия</p><h1>${title}</h1>${subtitle?`<p class="sub">${subtitle}</p>`:''}</div>${button}</div>`}
function table(list, registry=false){return `<div class="table-wrap"><table><thead><tr><th>${registry?'№ ТУ':'№ заявки'}</th><th>Заявитель / объект</th><th>Регион</th><th>Тип работ</th><th>Статус</th><th>Срок</th><th></th></tr></thead><tbody>${list.map(r=>`<tr><td><b>${esc(registry ? r.tu || '—' : r.id)}</b><small class="sub">${esc(r.date)}</small></td><td class="object">${esc(r.company)}<small>${esc(r.object)}</small></td><td>${esc(r.region)}</td><td>${esc(r.work)}</td><td><span class="status ${statusClass(r.status)}">${esc(r.status)}</span></td><td>${esc(r.due)}</td><td><button class="actions" data-detail="${esc(r.id)}">Открыть</button></td></tr>`).join('')}</tbody></table></div>`}
function overview(){return `<section class="content">${pageHead('Рабочая область','Добрый день, Диас. В вашем контуре 12 активных заявок.')}
<div class="metrics"><div class="metric"><label>Поступило заявок</label><b>${requests.length + 27}</b><small>↑ 12% за месяц</small></div><div class="metric" style="--accent:#d88918"><label>В работе</label><b>${requests.filter(x=>x.status==='В работе').length + 11}</b><small class="warn">5 требуют внимания</small></div><div class="metric" style="--accent:#168566"><label>Выдано ТУ</label><b>148</b><small>↑ 8% за месяц</small></div><div class="metric" style="--accent:#d05061"><label>Просрочено</label><b>4</b><small class="warn">Нужно обработать сегодня</small></div></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-head"><h2>Динамика обращений</h2><select aria-label="Период" style="width:120px"><option>7 дней</option><option>30 дней</option></select></div><div class="chart">${[['Пн',45],['Вт',68],['Ср',52],['Чт',83],['Пт',64],['Сб',34],['Вс',48]].map(([d,h])=>`<i class="bar" style="height:${h}%" data-label="${Math.round(h/7)}" data-day="${d}"></i>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2>Распределение по статусам</h2></div><div class="progress-row"><div><span>В работе</span><b>41%</b></div><div class="track"><i style="width:41%"></i></div></div><div class="progress-row"><div><span>На согласовании</span><b>27%</b></div><div class="track"><i style="width:27%;--accent:#8d63ce"></i></div></div><div class="progress-row"><div><span>ТУ выдано</span><b>22%</b></div><div class="track"><i style="width:22%;--accent:#168566"></i></div></div><div class="progress-row"><div><span>На проверке</span><b>10%</b></div><div class="track"><i style="width:10%;--accent:#d88918"></i></div></div></section></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-head"><h2>Последние заявки</h2><button class="link" data-go="requests">Все заявки →</button></div>${table(requests.slice(0,4))}</section><section class="panel"><div class="panel-head"><h2>Активность</h2></div><div class="activity"><div class="activity-item"><div class="activity-icon">✓</div><div><b>ТУ Д08-08-124/Т-08/26 утверждено</b><span>ЖК «Alma Park» · 18 минут назад</span></div></div><div class="activity-item"><div class="activity-icon">↗</div><div><b>Поступили технические данные от ЛТЦ</b><span>ЗТ-2026-00839 · 1 час назад</span></div></div><div class="activity-item"><div class="activity-icon">!</div><div><b>Заявка возвращена на доработку</b><span>ЗТ-2026-00837 · 2 часа назад</span></div></div></div></section></div></section>`}
function requestsView(){return `<section class="content">${pageHead('Заявки','Управляйте полным жизненным циклом технических условий.',`<button class="primary" id="new-request">+ Новая заявка</button>`)}<section class="panel"><div class="toolbar"><div class="search"><input id="query" placeholder="Поиск по номеру, компании или БИН" /></div><select class="filter" id="filter-status"><option value="">Все статусы</option><option>На проверке</option><option>В работе</option><option>На согласовании</option><option>На доработке</option><option>ТУ выдано</option></select><button class="secondary" id="export">⇩ Экспорт CSV</button></div><div id="request-table">${table(requests)}</div></section></section>`}
function registry(){let issued=requests.filter(r=>r.status==='ТУ выдано').map((r,i)=>({...r,tu:r.tu||`Д08-08-${124+i}/Т-08/26`}));return `<section class="content">${pageHead('Реестр выданных ТУ','Единый реестр технических условий и история выдачи.',`<button class="secondary" id="print-registry">⎙ Печать / PDF</button>`)}<section class="panel"><div class="toolbar"><div class="search"><input id="query" placeholder="Номер ТУ, БИН или компания" /></div><select class="filter"><option>Все регионы</option><option>г. Алматы</option></select><button class="secondary" id="export">⇩ Экспорт CSV</button></div>${issued.length?table(issued,true):'<p class="sub">Выданных ТУ пока нет. Измените статус заявки после утверждения.</p>'}</section></section>`}
function mapView(){return `<section class="content">${pageHead('Карта инфраструктуры','Схема объектов и точек подключения. Данные показаны в демонстрационном виде.',`<button class="primary" id="route">+ Построить трассу</button>`)}<section class="panel"><div class="map"><i class="pin" style="top:28%;left:29%" data-name="Узел связи №12"></i><i class="pin" style="top:51%;left:50%;--accent:#d88918" data-name="ККС-184"></i><i class="pin" style="top:39%;left:68%;--accent:#168566" data-name="Объект заявителя"></i><i class="pin" style="top:68%;left:76%;--accent:#8d63ce" data-name="АТС-4"></i></div><div class="map-legend"><span><i class="dot"></i>Узел связи</span><span><i class="dot" style="--accent:#d88918"></i>Кабельный колодец</span><span><i class="dot" style="--accent:#168566"></i>Объект заявителя</span><span><i class="dot" style="--accent:#8d63ce"></i>АТС</span></div></section></section>`}
function reports(){return `<section class="content">${pageHead('Аналитика и отчёты','Показатели эффективности процесса выдачи технических условий.',`<button class="secondary" id="export">⇩ Выгрузить отчёт</button>`)}<div class="kpis"><section class="panel report-card"><p class="sub">Средний срок выдачи</p><b>4,8 дня</b><p class="legend">На 0,6 дня быстрее прошлого месяца</p></section><section class="panel report-card"><p class="sub">Доля обработки в срок</p><b>94,6%</b><p class="legend">Целевой показатель: 95%</p></section><section class="panel report-card"><p class="sub">Самый активный регион</p><b>г. Алматы</b><p class="legend">38% всех заявок за период</p></section></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><h2>Заявки по регионам</h2></div><div class="chart">${[['Алматы',89],['Астана',69],['Караганда',53],['Шымкент',45],['Другие',34]].map(([d,h])=>`<i class="bar" style="height:${h}%" data-label="${h}" data-day="${d}"></i>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2>Типы работ</h2></div><div class="progress-row"><div><span>Прокладка кабеля</span><b>36%</b></div><div class="track"><i style="width:36%"></i></div></div><div class="progress-row"><div><span>Подключение к сети</span><b>29%</b></div><div class="track"><i style="width:29%;--accent:#00a6a6"></i></div></div><div class="progress-row"><div><span>Строительство ВОЛС</span><b>21%</b></div><div class="track"><i style="width:21%;--accent:#8d63ce"></i></div></div></section></div></section>`}
function settings(){return `<section class="content">${pageHead('Настройки','Управление шаблонами, нумерацией и правилами маршрутизации.')}<section class="panel"><h2>Нумерация технических условий</h2><p class="sub">Шаблон номера ТУ применяется при утверждении документа.</p><div style="display:flex;gap:10px;margin-top:20px;max-width:540px"><input value="Д08-08-{номер}/Т-{месяц}/{год}" /><button class="primary" id="save-settings">Сохранить</button></div></section></section>`}
function render(){document.querySelector('#breadcrumbs').innerHTML=`Рабочая область <span>/</span> ${({'overview':'Обзор','requests':'Заявки','registry':'Реестр ТУ','map':'Карта инфраструктуры','reports':'Отчёты','settings':'Настройки'})[view]}`;app.innerHTML=({overview,requests:requestsView,registry,map:mapView,reports,settings})[view]();document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));bind();}
function updateTable(){const q=document.querySelector('#query').value.toLowerCase();const status=document.querySelector('#filter-status')?.value||'';let rows=requests.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q)&&(!status||r.status===status));document.querySelector('#request-table').innerHTML=table(rows);}
function exportCsv(){let rows=[['Номер заявки','Компания','БИН','Объект','Регион','Тип работ','Статус'],...requests.map(r=>[r.id,r.company,r.bin,r.object,r.region,r.work,r.status])];let csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='реестр-ту.csv';a.click();URL.revokeObjectURL(a.href);toast('Экспорт подготовлен')}
function bind(){document.querySelector('#new-request')?.addEventListener('click',()=>dialog.showModal());document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;render()});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));document.querySelector('#query')?.addEventListener('input',updateTable);document.querySelector('#filter-status')?.addEventListener('change',updateTable);document.querySelectorAll('#export').forEach(b=>b.onclick=exportCsv);document.querySelector('#print-registry')?.addEventListener('click',()=>window.print());document.querySelector('#route')?.addEventListener('click',()=>toast('Режим построения трассы активирован'));document.querySelector('#save-settings')?.addEventListener('click',()=>toast('Настройки сохранены'));}
function openDetail(id){let r=requests.find(x=>x.id===id);details.innerHTML=`<div class="detail"><div class="modal-head"><div><p class="overline">${esc(r.id)}</p><h2>${esc(r.object)}</h2><p class="sub">${esc(r.company)} · БИН ${esc(r.bin)}</p></div><button class="close" id="close-detail">×</button></div><div class="form-grid"><fieldset><legend>Параметры заявки</legend><p><b>Регион:</b> ${esc(r.region)}</p><p><b>Тип работ:</b> ${esc(r.work)}</p><p><b>Ответственный:</b> ${esc(r.person)}</p><p><b>Документы:</b> Заявление.pdf, схема-трассы.pdf</p></fieldset><fieldset><legend>Управление</legend><label>Статус<select id="detail-status">${['На проверке','Запрос технических данных','В работе','На согласовании','На доработке','Согласована','Утверждена','ТУ выдано','Закрыта'].map(s=>`<option ${r.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Комментарий<textarea id="comment" placeholder="Комментарий для журнала действий"></textarea></label><button class="primary" id="save-status">Сохранить изменения</button></fieldset></div><div class="timeline"><div><b>Заявка подана</b><small>${esc(r.date)} · ${esc(r.company)}</small></div><div><b>${esc(r.status)}</b><small>Ответственный: ${esc(r.person)} · срок ${esc(r.due)}</small></div></div></div>`;details.showModal();document.querySelector('#close-detail').onclick=()=>details.close();document.querySelector('#save-status').onclick=()=>{r.status=document.querySelector('#detail-status').value;if(r.status==='ТУ выдано')r.tu=r.tu||`Д08-08-${Math.floor(Math.random()*800+100)}/Т-08/26`;save();details.close();toast('Статус и журнал изменений обновлены');render()}}
document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelector('#open-form').onclick=()=>dialog.showModal();document.querySelector('#request-form').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target),num=String(842+requests.length).padStart(5,'0'),r={id:`ЗТ-2026-${num}`,date:'25.08.2026',company:d.get('company'),bin:d.get('bin'),object:d.get('object'),region:d.get('region'),work:d.get('work'),status:'На проверке',person:'Назначается автоматически',due:'27 авг.'};requests.unshift(r);save();dialog.close();e.target.reset();view='requests';render();toast('Заявка принята и направлена в ответственное подразделение')});document.querySelector('#theme-toggle').onclick=()=>{let dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';document.querySelector('#theme-toggle').textContent=dark?'☀':'☾';localStorage.setItem('qoldau-theme',dark?'dark':'light')};if(localStorage.getItem('qoldau-theme')==='dark'){document.documentElement.dataset.theme='dark';document.querySelector('#theme-toggle').textContent='☀'}render();
